"""CDT wrapper — drives Check Point's Central Deployment Tool on a management server.

CDT pushes packages to *many* gateways at once. It runs ON the management server
(Expert mode, uid 0): binary ``$CDTDIR/CentralDeploymentTool``, config XML beside
it, and a candidates CSV that carries target selection AND upgrade order — the
CSV *is* the blast-radius/sequencing control. Long runs go under ``nohup`` so an
SSH drop doesn't kill a fleet deployment; progress is read from
``$CDTDIR/CDT_status(_brief).txt``. This wrapper builds inputs, issues commands
over a ``CommandRunner``, and parses outputs. Sequencing and safety decisions
live in the orchestrator/services. See .claude/memory/cdt-cpuse-domain.md.
"""

from __future__ import annotations

import csv
import io
import re
from dataclasses import dataclass, field
from xml.sax.saxutils import escape

from .errors import CDTError
from .transport.ssh import CommandRunner

CDT_DIR = "/opt/CPcdt"

# The single working candidates file this tool manages on the server. One
# deployment at a time — matching how CDT itself behaves.
CANDIDATES_FILENAME = "orch_candidates.csv"

_SAFE_PATH_RE = re.compile(r"/[A-Za-z0-9/._-]+")


@dataclass
class CandidatesFile:
    """Parsed candidates CSV: a header row plus data rows, kept generic because
    exact columns vary across CDT versions (Object Name, Cluster Name, IP,
    Version/JHF Take, State, Upgrade Order...). Row order == deployment order."""

    header: list[str] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)

    @classmethod
    def from_csv(cls, text: str) -> CandidatesFile:
        reader = csv.reader(io.StringIO(text))
        parsed = [row for row in reader if any(cell.strip() for cell in row)]
        if not parsed:
            return cls()
        return cls(header=parsed[0], rows=parsed[1:])

    def to_csv(self) -> str:
        buf = io.StringIO()
        writer = csv.writer(buf, lineterminator="\n")
        if self.header:
            writer.writerow(self.header)
        writer.writerows(self.rows)
        return buf.getvalue()


@dataclass(frozen=True)
class CDTStatus:
    """Snapshot of a CDT run as reported by the status files."""

    running: bool
    brief: str

    @property
    def looks_failed(self) -> bool:
        return bool(re.search(r"\bfail(ed|ure)?\b", self.brief, re.IGNORECASE))


def build_config_xml(
    package_path: str,
    *,
    cpuse_rpm_path: str | None = None,
    pre_script: str | None = None,
    post_script: str | None = None,
) -> str:
    """Render ``CentralDeploymentTool.xml`` (simple mode): WHAT to deploy.

    Paths are validated (they land in a root-executed tool's config) and
    XML-escaped. The candidates CSV — WHERE to deploy — is managed separately.
    """
    for label, path in (
        ("package", package_path),
        ("CPUSE RPM", cpuse_rpm_path),
        ("pre-script", pre_script),
        ("post-script", post_script),
    ):
        if path is not None and not _SAFE_PATH_RE.fullmatch(path):
            raise CDTError(f"suspicious {label} path for CDT config: {path!r}")

    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        "<!-- Generated by chkp-cpuse-orch; do not hand-edit on the server. -->",
        "<CentralDeploymentTool>",
        "  <Deployment>",
        f"    <PackageToInstall>{escape(package_path)}</PackageToInstall>",
    ]
    if cpuse_rpm_path:
        lines.append(f"    <CPUSE>{escape(cpuse_rpm_path)}</CPUSE>")
    if pre_script:
        lines.append(f"    <PreInstallationScript>{escape(pre_script)}</PreInstallationScript>")
    if post_script:
        lines.append(f"    <PostInstallationScript>{escape(post_script)}</PostInstallationScript>")
    lines += ["  </Deployment>", "</CentralDeploymentTool>", ""]
    return "\n".join(lines)


class CDT:
    """Central Deployment Tool operations, executed on a management server host
    over SSH (Expert mode shell)."""

    def __init__(self, runner: CommandRunner, *, cdt_dir: str = CDT_DIR) -> None:
        self._runner = runner
        self._dir = cdt_dir

    # -- paths -------------------------------------------------------------------

    @property
    def binary(self) -> str:
        return f"{self._dir}/CentralDeploymentTool"

    @property
    def config_path(self) -> str:
        return f"{self._dir}/CentralDeploymentTool.xml"

    @property
    def candidates_path(self) -> str:
        return f"{self._dir}/{CANDIDATES_FILENAME}"

    @property
    def execute_log_path(self) -> str:
        return f"{self._dir}/orch_execute.log"

    # -- read-only ----------------------------------------------------------------

    def is_available(self) -> bool:
        return self._runner.run(f"test -x {self.binary}").ok

    def read_candidates(self) -> CandidatesFile:
        result = self._runner.run(f"cat {self.candidates_path}")
        if not result.ok:
            raise CDTError(
                f"no candidates file at {self.candidates_path} — run generate first "
                f"(rc={result.exit_status})"
            )
        return CandidatesFile.from_csv(result.stdout)

    def status(self) -> CDTStatus:
        """Process liveness + brief status text (empty string if none yet)."""
        running = self._runner.run("pgrep -f CentralDeploymentTool >/dev/null").ok
        brief = self._runner.run(f"cat {self._dir}/CDT_status_brief.txt 2>/dev/null")
        return CDTStatus(running=running, brief=brief.stdout.strip())

    def full_status(self) -> str:
        result = self._runner.run(f"cat {self._dir}/CDT_status.txt 2>/dev/null")
        return result.stdout

    # -- mutating (caller gates on safety) -----------------------------------------

    def generate(self) -> None:
        """Generate the candidates CSV from the configured package (simple mode)."""
        self._invoke(f"{self.binary} -generate {self.candidates_path}", "generate")

    def preparations(self, *, extended: bool = False) -> None:
        """Front-load slow work (ship packages, pre-scripts; extended also
        updates CPUSE agents and imports packages on targets)."""
        verb = "-extended_preparations" if extended else "-preparations"
        self._invoke(f"{self.binary} {verb} {self.candidates_path}", "preparations")

    def start_execute(self) -> None:
        """Launch ``-execute`` under nohup and return immediately. The run
        continues on the server even if our SSH session drops; progress is
        polled via ``status()``. Refuses to start if CDT is already running."""
        if self.status().running:
            raise CDTError("a CentralDeploymentTool process is already running on this server")
        result = self._runner.run(
            f"nohup {self.binary} -execute {self.candidates_path} "
            f"> {self.execute_log_path} 2>&1 & echo started"
        )
        if not result.ok or "started" not in result.stdout:
            raise CDTError(f"failed to launch CDT execute: {result.stderr.strip()}")

    def _invoke(self, command: str, action: str) -> None:
        # Generate/preparations run in the foreground with a generous timeout;
        # only execute (fleet-wide, hours) goes through nohup.
        result = self._runner.run(command, timeout=3600.0)
        if not result.ok:
            detail = result.stderr.strip() or result.stdout.strip()
            raise CDTError(f"CDT {action} failed (rc={result.exit_status}): {detail}")
